from PyQt5.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QCheckBox, QPushButton, QPlainTextEdit

class LogsTab(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)
        filter_row = QHBoxLayout()
        self.systemLogCheck = QCheckBox('System Logs')
        self.systemLogCheck.setObjectName('systemLogCheck')
        self.packetLogCheck = QCheckBox('Packet Logs')
        self.packetLogCheck.setObjectName('packetLogCheck')
        self.mlLogCheck = QCheckBox('ML Logs')
        self.mlLogCheck.setObjectName('mlLogCheck')
        self.exportLogsButton = QPushButton('Export Logs')
        self.exportLogsButton.setObjectName('exportLogsButton')
        filter_row.addWidget(self.systemLogCheck)
        filter_row.addWidget(self.packetLogCheck)
        filter_row.addWidget(self.mlLogCheck)
        filter_row.addStretch()
        filter_row.addWidget(self.exportLogsButton)
        layout.addLayout(filter_row)
        self.logOutput = QPlainTextEdit()
        self.logOutput.setObjectName('logOutput')
        self.logOutput.setReadOnly(True)
        layout.addWidget(self.logOutput) 