from PyQt5.QtWidgets import QWidget, QFormLayout, QComboBox, QPushButton, QLabel, QHBoxLayout, QCheckBox

class SettingsTab(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        form = QFormLayout(self)
        self.defaultInterfaceCombo = QComboBox()
        self.defaultInterfaceCombo.setObjectName('defaultInterfaceCombo')
        self.autosaveLocationButton = QPushButton('Choose...')
        self.autosaveLocationButton.setObjectName('autosaveLocationButton')
        self.autosaveLocationLabel = QLabel('Not set')
        self.autosaveLocationLabel.setObjectName('autosaveLocationLabel')
        autosave_row = QHBoxLayout()
        autosave_row.addWidget(self.autosaveLocationButton)
        autosave_row.addWidget(self.autosaveLocationLabel)
        autosave_widget = QWidget()
        autosave_widget.setLayout(autosave_row)
        self.soundAlertsCheck = QCheckBox('Enable Sound Alerts')
        self.soundAlertsCheck.setObjectName('soundAlertsCheck')
        self.mlModelPathButton = QPushButton('Choose...')
        self.mlModelPathButton.setObjectName('mlModelPathButton')
        self.mlModelPathLabel = QLabel('Not set')
        self.mlModelPathLabel.setObjectName('mlModelPathLabel')
        mlmodel_row = QHBoxLayout()
        mlmodel_row.addWidget(self.mlModelPathButton)
        mlmodel_row.addWidget(self.mlModelPathLabel)
        mlmodel_widget = QWidget()
        mlmodel_widget.setLayout(mlmodel_row)
        self.themeToggle = QComboBox()
        self.themeToggle.setObjectName('themeToggle')
        self.themeToggle.addItems(['Dark', 'Light'])
        form.addRow('Default Interface:', self.defaultInterfaceCombo)
        form.addRow('Autosave Location:', autosave_widget)
        form.addRow('', self.soundAlertsCheck)
        form.addRow('ML Model Path:', mlmodel_widget)
        form.addRow('Theme:', self.themeToggle) 